name: phone_log
description: A new flutter plugin project.
version: 0.0.3
author: Jiaming Cheng <jiamingc@google.com>
homepage: https://github.com/jiajiabingcheng/phone_log

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fixnum: ^0.10.9

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.jiajiabingcheng.phonelog
    pluginClass: PhoneLogPlugin

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
